### ISSUE TITLE
Feature Request: button to hide points cloud and grid

### ISSUE THREAD

**Issue by jouany** [rajubd49/ARKit-Sample-ObjC#1]
Dear Raju
Thank you very much for your program that I try to understand and upgrade with more objects for better understanding of 3D supported format and default size to setup in ARKit. What you did is great help for me.

Would you be kind enough to add a feature with a new button that would hide the yellow points cloud, the blue grid, potentially time and cell phone bars in a way it becomes possible to use IOS11 screen recording feature to capture only what camera is seing and 3D objects.

Thanks a lot

**Comment by rajubd49** [comment]
Hi, 

Sorry for late response. 

Please check the new implementation, you issue is resolved now.
